apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: testadminbinding
  namespace: test
subjects:
# You can specify more than one "subject"
- kind: ServiceAccount
  name: foo 
  apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role # Role or ClusterRole
  name: testadmin # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: ""
